import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

public class Dealer {
	
	public List<Card> createNewDeck() {
		List<Card> deck = new ArrayList<Card>();
		
		Card card1 = new Card("Clubs", "Ace", 1);
		deck.add(card1);
		Card card2 = new Card("Clubs", "2", 2);
		deck.add(card2);
		Card card3 = new Card("Clubs", "3", 3);
		deck.add(card3);
		Card card4 = new Card("Clubs", "4", 4);
		deck.add(card4);
		Card card5 = new Card("Clubs", "5", 5);
		deck.add(card5);
		Card card6 = new Card("Clubs", "6", 6);
		deck.add(card6);
		Card card7 = new Card("Clubs", "7", 7);
		deck.add(card7);
		Card card8 = new Card("Clubs", "8", 8);
		deck.add(card8);
		Card card9 = new Card("Clubs", "9", 9);
		deck.add(card9);
		Card card10 = new Card("Clubs", "10", 10);
		deck.add(card10);
		Card card11 = new Card("Clubs", "Jack", 10);
		deck.add(card11);
		Card card12 = new Card("Clubs", "Queen", 10);
		deck.add(card12);
		Card card13 = new Card("Clubs", "King", 10);
		deck.add(card13);
		//Card card14 = new Card("Clubs", "Ace", 11);
		//deck.add(card14);
		Card card15 = new Card("Hearts", "Ace", 1);
		deck.add(card15);
		Card card16 = new Card("Hearts", "2", 2);
		deck.add(card16);
		Card card17 = new Card("Hearts", "3", 3);
		deck.add(card17);
		Card card18 = new Card("Hearts", "4", 4);
		deck.add(card18);
		Card card19 = new Card("Hearts", "5", 5);
		deck.add(card19);
		Card card20 = new Card("Hearts", "6", 6);
		deck.add(card20);
		Card card21 = new Card("Hearts", "7", 7);
		deck.add(card21);
		Card card22 = new Card("Hearts", "8", 8);
		deck.add(card22);
		Card card23 = new Card("Hearts", "9", 9);
		deck.add(card23);
		Card card24 = new Card("Hearts", "10", 10);
		deck.add(card24);
		Card card25 = new Card("Hearts", "Jack", 10);
		deck.add(card25);
		Card card26 = new Card("Hearts", "Queen", 10);
		deck.add(card26);
		Card card27 = new Card("Hearts", "King", 10);
		deck.add(card27);
		//Card card28 = new Card("Hearts", "Ace", 11);
		//deck.add(card28);
		Card card29 = new Card("Diamonds", "Ace", 1);
		deck.add(card29);
		Card card30 = new Card("Diamonds", "2", 2);
		deck.add(card30);
		Card card31 = new Card("Diamonds", "3", 3);
		deck.add(card31);
		Card card32 = new Card("Diamonds", "4", 4);
		deck.add(card32);
		Card card33 = new Card("Diamonds", "5", 5);
		deck.add(card33);
		Card card34 = new Card("Diamonds", "6", 6);
		deck.add(card34);
		Card card35= new Card("Diamonds", "7", 7);
		deck.add(card35);
		Card card36 = new Card("Diamonds", "8", 8);
		deck.add(card36);
		Card card37 = new Card("Diamonds", "9", 9);
		deck.add(card37);
		Card card38 = new Card("Diamonds", "10", 10);
		deck.add(card38);
		Card card39 = new Card("Diamonds", "Jack", 10);
		deck.add(card39);
		Card card40 = new Card("Diamonds", "Queen", 10);
		deck.add(card40);
		Card card41 = new Card("Diamonds", "King", 10);
		deck.add(card41);
		//Card card42 = new Card("Diamonds", "Ace", 11);
		//deck.add(card42);
		Card card43 = new Card("Spades", "Ace", 1);
		deck.add(card43);
		Card card44 = new Card("Spades", "2", 2);
		deck.add(card44);
		Card card45 = new Card("Spades", "3", 3);
		deck.add(card45);
		Card card46 = new Card("Spades", "4", 4);
		deck.add(card46);
		Card card47 = new Card("Spades", "5", 5);
		deck.add(card47);
		Card card48 = new Card("spades", "6", 6);
		deck.add(card48);
		Card card49= new Card("Spades", "7", 7);
		deck.add(card49);
		Card card50 = new Card("Spades", "8", 8);
		deck.add(card50);
		Card card51 = new Card("Spades", "9", 9);
		deck.add(card51);
		Card card52 = new Card("Spades", "10", 10);
		deck.add(card52);
		Card card53 = new Card("spades", "Jack", 10);
		deck.add(card53);
		Card card54 = new Card("Spades", "Queen", 10);
		deck.add(card54);
		Card card55 = new Card("Spades", "King", 10);
		deck.add(card55);
		//Card card56 = new Card("Spades", "Ace", 11);
		//deck.add(card56);
		
		return deck;
	}
	
	public List<Card> shuffle(List<Card> cards ) {
		Collections.shuffle(cards);
		return cards;
	}
}